on: push
name: Build and deploy
    web-deploy: 
      name: Deploy
      steps:
      -name: Get latest code
      uses: action/checkout@v3

      -name: Sync files
      uses: SamiKrkland/FTP-Deploy-Action@v4.3.4
      with:  
      server: ftp.wide.sk
      username: ${{ secrets.FTPUSERNAME }}
      password: ${{ secrets.FTPPASSWORD }}
      protocol: ftps
      server-dir: /www_root_wide/
      
